//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('PreventionTips')
export class PreventionTipsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  tipTitle: string;

  @Column('text', { nullable: true })
  description: string;

  @Column('text', { nullable: true })
  preventiveMeasures: string;

  @Column('text', { nullable: true })
  imageUrl: string;
}
