//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Resources')
export class ResourcesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  resourceName: string;

  @Column('text', { nullable: true })
  description: string;

  @Column('text', { nullable: true })
  resourceUrl: string;
}
