//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('UserStories')
export class UserStoriesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  storyTitle: string;

  @Column('text', { nullable: true })
  story: string;

  @Column('text', { nullable: true })
  imageUrl: string;
}
