//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="D-Fender (Dengue-Defense)" />
    <CardContent>
      An app for dengue awareness with different sections including Dengue
      Information, Prevention Tips, Symptoms, Treatment Options, User Stories,
      and Resources.
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
